### PR TITLE
feat(Resource Controller): add "onetime_credentials" property in ResourceInstance and ResourceKey schemas

### PR DESCRIPTION
**Pull request by arshabbir**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pyrooka — CHANGES_REQUESTED** [review]
Code changes are looking good, but please attach the result of the integration and examples test run. Also, you need to sign the CLA here too.

**Comment by arshabbir** [comment]
[output_latest_examples.txt](https://github.com/user-attachments/files/16142328/output_latest_examples.txt)
[output_latest_integration.txt](https://github.com/user-attachments/files/16142329/output_latest_integration.txt)
[output_latest_npm_run_all.txt](https://github.com/user-attachments/files/16142330/output_latest_npm_run_all.txt)

**Review by pyrooka — APPROVED** [review]
Thanks for the test result! Now all you need to do is signing the CLA.

**Pull request merged**
