### PR TITLE
fix: add labels to example output

### PR DESCRIPTION
**Pull request by Andras-Csanyi**
## PR summary
This PR adds labels to example output. This way it is easier to identify which output section belongs to which method.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by padamstx — APPROVED** [review]
LGTM

**Review by pyrooka — APPROVED** [review]
Looks good!

**Review by padamstx — APPROVED** [review]
It looks like for "void" operations that do not return an actual result object, we should be displaying only the status code (like in the Go and Java examples), but it looks like we are displaying the `res.result` field nonetheless.  I think this needs to be fixed.  But, I'll approve now to avoid another re-review.

**Comment by Andras-Csanyi** [comment]
> It looks like for "void" operations that do not return an actual result object, we should be displaying only the status code (like in the Go and Java examples), but it looks like we are displaying the `res.result` field nonetheless. I think this needs to be fixed. But, I'll approve now to avoid another re-review.

Oh, shoot... It is already fixed.

**Pull request merged**
