### PR TITLE
feat(Partner Management APIs): add new service to project

### PR DESCRIPTION
**Pull request by manukm-ibm**
## PR summary

Adding new partner API to fetch resource usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/cosell/partner.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2063

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by manukm-ibm** [comment]
Integration test results
Screenshot 2024-10-22 at 1 21 20 PM

Example results
Screenshot 2024-10-22 at 2 31 57 PM

**Comment by padamstx** [comment]
@manukm-ibm Manu, one small change that is needed.  In the project's .gitignore file, please remove the entries for the two services you are removing, and add a new entry for the new service.

**Review by padamstx — CHANGES_REQUESTED** [review]
Changes look good, but just need the small change to .gitignore

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
