### PR TITLE
feat(Usage Reports): add "created_by_email_id" to Offer schema

### PR DESCRIPTION
**Pull request by Jdatechong**
## PR summary

updated offers to have the created_by_email_id field

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

updated offers to have the created_by_email_id field

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

Test results:
```
 PASS  test/unit/global-search.v2.test.js (5.786 s)
 PASS  test/unit/usage-metering.v4.test.js (5.803 s)
 PASS  test/unit/partner-usage-reports.v1.test.js (5.827 s)
 PASS  test/unit/ibm-cloud-shell.v1.test.js (6.077 s)
 PASS  test/unit/open-service-broker.v1.test.js (6.047 s)
 PASS  test/unit/partner-billing-units.v1.test.js (6.339 s)
 PASS  test/unit/resource-manager.v2.test.js (6.461 s)
 PASS  test/unit/global-tagging.v1.test.js (6.345 s)
 PASS  test/unit/global-catalog.v1.test.js (6.45 s)
 PASS  test/unit/enterprise-usage-reports.v1.test.js (6.541 s)
 PASS  test/unit/user-management.v1.test.js (6.776 s)
 PASS  test/unit/common.test.js
 PASS  test/unit/iam-policy-management.v1.test.js (7.083 s)
 PASS  test/unit/iam-access-groups.v2.test.js (7.226 s)
 PASS  test/unit/resource-controller.v2.test.js (7.328 s)
 PASS  test/unit/iam-identity.v1.test.js (7.68 s)
 PASS  test/unit/enterprise-billing-units.v1.test.js
 PASS  test/unit/enterprise-management.v1.test.js
 PASS  test/unit/case-management.v1.test.js
 PASS  test/unit/context-based-restrictions.v1.test.js
 PASS  test/unit/usage-reports.v4.test.js
 PASS  test/unit/catalog-management.v1.test.js
----------------------------|---------|----------|---------|---------|------------------------------------------------------------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                      
----------------------------|---------|----------|---------|---------|------------------------------------------------------------------------
All files                   |   98.36 |    89.61 |     100 |   98.31 |                                                                        
 case-management            |    98.8 |    88.46 |     100 |   98.78 |                                                                        
  v1.ts                     |    98.8 |    88.46 |     100 |   98.78 | 129,1246,1269                                                          
 catalog-management         |   97.76 |    85.41 |     100 |   97.67 |                                                                        
  v1.ts                     |   97.76 |    85.41 |     100 |   97.67 | ...9,13302,13358,13381,13437,13460,13519,13542,13601,13624,13683,13706 
 context-based-restrictions |    98.3 |    92.94 |     100 |   98.29 |                                                                        
  v1.ts                     |    98.3 |    92.94 |     100 |   98.29 | 142,499,642,1102                                                       
 enterprise-billing-units   |    96.4 |    79.06 |     100 |   96.15 |                                                                        
  v1.ts                     |    96.4 |    79.06 |     100 |   96.15 | 185,594,617,676,699                                                    
 enterprise-management      |   96.94 |     79.1 |     100 |    96.8 |                                                                        
  v1.ts                     |   96.94 |     79.1 |     100 |    96.8 | 209,552,858,1502,1525,1584,1607,1666,1689                              
 enterprise-usage-reports   |   95.89 |    78.57 |     100 |   95.58 |                                                                        
  v1.ts                     |   95.89 |    78.57 |     100 |   95.58 | 147,388,411                                                            
 global-catalog             |     100 |    94.28 |     100 |     100 |                                                                        
  v1.ts                     |     100 |    94.28 |     100 |     100 | 88,1166                                                                
 global-search              |    98.3 |    88.46 |     100 |   98.27 |                                                                        
  v2.ts                     |    98.3 |    88.46 |     100 |   98.27 | 200                                                                    
 global-tagging             |   98.59 |    92.98 |     100 |   98.58 |                                                                        
  v1.ts                     |   98.59 |    92.98 |     100 |   98.58 | 171,331                                                                
 iam-access-groups          |   98.58 |    87.38 |     100 |   98.54 |                                                                        
  v2.ts                     |   98.58 |    87.38 |     100 |   98.54 | 3779,3802,3860,3883,3941,3964,4022,4045                                
 iam-identity               |   99.21 |    95.84 |     100 |   99.21 |                                                                        
  v1.ts                     |   99.21 |    95.84 |     100 |   99.21 | 147,296,722,2597,2912,2974,3724,4038,4112                              
 iam-policy-management      |   99.84 |     98.8 |     100 |   99.84 |                                                                        
  v1.ts                     |   99.84 |     98.8 |     100 |   99.84 | 653                                                                    
 ibm-cloud-shell            |     100 |     92.3 |     100 |     100 |                                                                        
  v1.ts                     |     100 |     92.3 |     100 |     100 | 83                                                                     
 lib                        |     100 |      100 |     100 |     100 |                                                                        
  common.ts                 |     100 |      100 |     100 |     100 |                                                                        
 open-service-broker        |     100 |    94.44 |     100 |     100 |                                                                        
  v1.ts                     |     100 |    94.44 |     100 |     100 | 83                                                                     
 partner-billing-units      |     100 |    95.12 |     100 |     100 |                                                                        
  v1.ts                     |     100 |    95.12 |     100 |     100 | 85,229                                                                 
 partner-usage-reports      |   97.36 |    83.87 |     100 |   97.18 |                                                                        
  v1.ts                     |   97.36 |    83.87 |     100 |   97.18 | 413,436                                                                
 resource-controller        |   96.93 |    81.81 |     100 |   96.78 |                                                                        
  v2.ts                     |   96.93 |    81.81 |     100 |   96.78 | ...04,2927,2986,3009,3068,3091,3150,3173,3232,3255,3314,3337,3396,3419 
 resource-manager           |     100 |    93.33 |     100 |     100 |                                                                        
  v2.ts                     |     100 |    93.33 |     100 |     100 | 85                                                                     
 usage-metering             |     100 |    91.66 |     100 |     100 |                                                                        
  v4.ts                     |     100 |    91.66 |     100 |     100 | 87                                                                     
 usage-reports              |   97.97 |     90.9 |     100 |   97.88 |                                                                        
  v4.ts                     |   97.97 |     90.9 |     100 |   97.88 | 2047,2070,2131,2154,2212,2235,2293,2316                                
 user-management            |    98.2 |    82.85 |     100 |   98.14 |                                                                        
  v1.ts                     |    98.2 |    82.85 |     100 |   98.14 | 483,1003,1026                                                          
----------------------------|---------|----------|---------|---------|------------------------------------------------------------------------

Test Suites: 22 passed, 22 total
Tests:       1656 passed, 1656 total
Snapshots:   0 total
Time:        11.03 s
```

### CODE REVIEW

**Review by pyrooka — APPROVED** [review]
Looks good! The only question I have is: have you signed the CLA?

**Comment by Jdatechong** [comment]
Yes, I've signed the CLA a few of times now :)

**Comment by pyrooka** [comment]
> Yes, I've signed the CLA a few of times now :)

Okay, thank you! Sometimes the CLA check get stuck, that's why I asked.

**Review by pyrooka — CHANGES_REQUESTED** [review]
@Jdatechong Please re-gen the code by using the latest version of the generator. Thank you!

**Review by pyrooka — APPROVED** [review]
Looks good!

**Pull request merged**
