### PR TITLE
docs: fix documentation

### PR DESCRIPTION
**Pull request by Andras-Csanyi**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Andras-Csanyi** [comment]
Missing examples:

```
    "/v1/profiles": {},
    "/v1/profiles/{profile-id}": {},
    "/v1/profiles/{profile-id}/rules": {},
    "/v1/profiles/{profile-id}/rules/{rule-id}": {},
    "/v1/profiles/{profile-id}/links": {},
    "/v1/profiles/{profile-id}/links/{link-id}": {},
```

**Comment by Andras-Csanyi** [comment]
@pooraniss-ibm The modified documentation tags were the problem. The generated example files on my machine look good. Once these PRs are merged in you can re-gen the example files. The reason I skip it now that the node sdk missing a few examples (see previous comment on this PR)  and I don't know whether it is by mistaken or not.

**Comment by pooraniss-ibm** [comment]
@Andras-Csanyi 
"node sdk missing a few examples"
sorry I double checked it, I don't think any examples are missing from the examples file. they do include all of them related to trusted profiles. 
cc: @padamstx

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
